general:
  assetBaseDir: config/assets
  primaryLanguage: de
  secondaryLanguage: en
  scoreLabels:
    circularity:
      en: Circularity
      de: Kreislauf
    happiness:
      en: Happiness
      de: Zufriedenheit
