layers:
  - url: background_static_x0_y0.webp
    condition: 'true'
  - modelVisualization
  - url: government_static_x794_y1705.webp
    condition: 'true'
  - url: reduce_cellphone_x1647_y1346.webp
    condition: 'true'
  - url: reduce_walkingman_x1471_y1347.webp
    condition: 'true'
