/* tslint:disable */
/* eslint-disable */
/**
 * This file is generated by core-types-ts on behalf of typeconv, DO NOT EDIT.
 * For more information, see:
 *  - {@link https://github.com/grantila/core-types-ts}
 *  - {@link https://github.com/grantila/typeconv}
 */

export interface InitialParametersConfig {
  abandonExcessRate: number;
  abandonRate: number;
  acquireRate: number;
  breakRate: number;
  capacityAdjustmentRate: number;
  disposeIncentive: number;
  disposeRate: number;
  landfillIncentive: number;
  landfillRate: number;
  naturalResourcesIncentive: number;
  newPhoneProductionRate: number;
  newlyProducedPhoneIncentive: number;
  numberOfUsers: number;
  phonesPerUserGoal: number;
  recycleRate: number;
  recyclingIncentive: number;
  refurbishmentIncentive: number;
  refurbishmentRate: number;
  repairIncentive: number;
  repairRate: number;
  reuseIncentive: number;
}

export interface InitialStocksConfig {
  capacityOfNewlyProducedPhones: number;
  capacityOfRecycledMaterials: number;
  capacityOfRefurbishedPhones: number;
  capacityOfRepairedPhones: number;
  phonesInUse: number;
  supplyOfBrokenPhones: number;
  supplyOfDisposedPhones: number;
  supplyOfHibernatingPhones: number;
  supplyOfNewlyProducedPhones: number;
  supplyOfRecycledMaterials: number;
  supplyOfRefurbishedPhones: number;
  supplyOfRepairedPhones: number;
}

export interface ParameterTransformConfig {
  id: string;
  script: string;
}

export interface BasicSlotConfig {
  id: string;
  x: number;
  y: number;
  angle?: number;
}

export interface BasicSlotGroupConfig {
  id: string;
  type: 'basic';
  slots: BasicSlotConfig[];
  parameterTransformIds: string[];
}

export interface SlotWithCardConfig {
  id: string;
  x: number;
  y: number;
  angle?: number;
  card: {
    x: number;
    y: number;
    angle?: number;
  };
}

export interface I18NStringConfig {
  [key: string]: string;
}

export interface ActionCardConfig {
  id: string;
  url: string;
  title: I18NStringConfig;
  description: I18NStringConfig;
}

export interface ActionCardSlotGroupConfig {
  id: string;
  type: 'action-card';
  slots: SlotWithCardConfig[];
  cards: ActionCardConfig[];
}

export interface EventCardConfig {
  id: string;
  url: string;
  title: I18NStringConfig;
  description: I18NStringConfig;
}

export interface EventCardSlotGroupConfig {
  id: string;
  type: 'event-card';
  slots: SlotWithCardConfig[];
  cards: EventCardConfig[];
}

export type SlotGroup =
  | BasicSlotGroupConfig
  | ActionCardSlotGroupConfig
  | EventCardSlotGroupConfig;

export interface TriggerConditionConfig {
  condition: string;
  url: string;
}

export interface TriggerConfig {
  id: string;
  events: TriggerConditionConfig[];
}

export interface Config {
  general: {
    backgroundImage: string;
  };
  model: {
    initialParameters: InitialParametersConfig;
    initialStocks: InitialStocksConfig;
  };
  simulation: {
    deltaPerSecond: number;
    maxStepSize: number;
  };
  parameterTransforms: ParameterTransformConfig[];
  interaction: {
    slotActivationDelay: number;
    slotDeactivationDelay: number;
    slotGroups: SlotGroup[];
  };
  triggers: TriggerConfig[];
}
