$schema: http://json-schema.org/draft-07/schema#
title: Config
type: object
properties:
  general:
    type: object
    properties:
      assetBaseDir:
        type: string
    required:
      - assetBaseDir
    additionalProperties: false
  model:
    type: object
    properties:
      initialParameters:
        $ref: '#/definitions/InitialParametersConfig'
      initialStocks:
        $ref: '#/definitions/InitialStocksConfig'
    required:
      - initialParameters
      - initialStocks
    additionalProperties: false
  simulation:
    type: object
    properties:
      deltaPerSecond:
        type: number
      maxStepSize:
        type: number
    required:
      - deltaPerSecond
      - maxStepSize
    additionalProperties: false
  parameterTransforms:
    type: array
    items:
      $ref: '#/definitions/ParameterTransformConfig'
  interaction:
    type: object
    properties:
      slotActivationDelay:
        type: number
      slotDeactivationDelay:
        type: number
      slotGroups:
        type: array
        items:
          $ref: '#/definitions/SlotGroup'
    required:
      - slotActivationDelay
      - slotDeactivationDelay
      - slotGroups
    additionalProperties: false
  triggers:
    type: array
    items:
      $ref: '#/definitions/TriggerConfig'
required:
  - general
  - model
  - simulation
  - parameterTransforms
  - interaction
  - triggers
additionalProperties: false
definitions:
  InitialParametersConfig:
    type: object
    properties:
      abandonExcessRate:
        type: number
      abandonRate:
        type: number
      acquireRate:
        type: number
      breakRate:
        type: number
      capacityAdjustmentRate:
        type: number
      disposeIncentive:
        type: number
      disposeRate:
        type: number
      landfillIncentive:
        type: number
      landfillRate:
        type: number
      naturalResourcesIncentive:
        type: number
      newPhoneProductionRate:
        type: number
      newlyProducedPhoneIncentive:
        type: number
      numberOfUsers:
        type: number
      phonesPerUserGoal:
        type: number
      recycleRate:
        type: number
      recyclingIncentive:
        type: number
      refurbishmentIncentive:
        type: number
      refurbishmentRate:
        type: number
      repairIncentive:
        type: number
      repairRate:
        type: number
      reuseIncentive:
        type: number
    required:
      - abandonExcessRate
      - abandonRate
      - acquireRate
      - breakRate
      - capacityAdjustmentRate
      - disposeIncentive
      - disposeRate
      - landfillIncentive
      - landfillRate
      - naturalResourcesIncentive
      - newPhoneProductionRate
      - newlyProducedPhoneIncentive
      - numberOfUsers
      - phonesPerUserGoal
      - recycleRate
      - recyclingIncentive
      - refurbishmentIncentive
      - refurbishmentRate
      - repairIncentive
      - repairRate
      - reuseIncentive
    additionalProperties: false
  InitialStocksConfig:
    type: object
    properties:
      capacityOfNewlyProducedPhones:
        type: number
      capacityOfRecycledMaterials:
        type: number
      capacityOfRefurbishedPhones:
        type: number
      capacityOfRepairedPhones:
        type: number
      phonesInUse:
        type: number
      supplyOfBrokenPhones:
        type: number
      supplyOfDisposedPhones:
        type: number
      supplyOfHibernatingPhones:
        type: number
      supplyOfNewlyProducedPhones:
        type: number
      supplyOfRecycledMaterials:
        type: number
      supplyOfRefurbishedPhones:
        type: number
      supplyOfRepairedPhones:
        type: number
    required:
      - capacityOfNewlyProducedPhones
      - capacityOfRecycledMaterials
      - capacityOfRefurbishedPhones
      - capacityOfRepairedPhones
      - phonesInUse
      - supplyOfBrokenPhones
      - supplyOfDisposedPhones
      - supplyOfHibernatingPhones
      - supplyOfNewlyProducedPhones
      - supplyOfRecycledMaterials
      - supplyOfRefurbishedPhones
      - supplyOfRepairedPhones
    additionalProperties: false
  ParameterTransformConfig:
    type: object
    properties:
      id:
        type: string
      script:
        type: string
    required:
      - id
      - script
    additionalProperties: false
  BasicSlotConfig:
    type: object
    properties:
      id:
        type: string
      x:
        type: number
      'y':
        type: number
      angle:
        type: number
        default: 0
    required:
      - id
      - x
      - 'y'
    additionalProperties: false
  BasicSlotGroupConfig:
    type: object
    properties:
      id:
        type: string
        pattern: ^((?!internal).)*$
      type:
        type: string
        enum:
          - basic
      slots:
        type: array
        items:
          $ref: '#/definitions/BasicSlotConfig'
      parameterTransformIds:
        type: array
        items:
          type: string
    required:
      - id
      - type
      - slots
      - parameterTransformIds
    additionalProperties: false
  SlotWithCardConfig:
    type: object
    properties:
      id:
        type: string
      x:
        type: number
      'y':
        type: number
      angle:
        type: number
        default: 0
      card:
        type: object
        properties:
          x:
            type: number
          'y':
            type: number
          angle:
            type: number
            default: 0
        required:
          - x
          - 'y'
        additionalProperties: false
    required:
      - id
      - x
      - 'y'
      - card
    additionalProperties: false
  CardConfig:
    type: object
    properties:
      parameterTransformId:
        type: string
      url:
        type: string
        pattern: _x[+-]?[0-9]+_y[+-]?[0-9]+\.[a-zA-Z0-9]+$
    required:
      - parameterTransformId
      - url
    additionalProperties: false
  ActionCardSlotGroupConfig:
    type: object
    properties:
      id:
        type: string
        pattern: ^((?!internal).)*$
      type:
        type: string
        enum:
          - action-card
      slots:
        type: array
        items:
          $ref: '#/definitions/SlotWithCardConfig'
      cards:
        type: array
        items:
          $ref: '#/definitions/CardConfig'
    required:
      - id
      - type
      - slots
      - cards
    additionalProperties: false
  CardSlotConfig:
    type: object
    properties:
      id:
        type: string
      x:
        type: number
      'y':
        type: number
      angle:
        type: number
        default: 0
    required:
      - id
      - x
      - 'y'
      - angle
    additionalProperties: false
  EventCardSlotGroupConfig:
    type: object
    properties:
      id:
        type: string
        pattern: ^((?!internal).)*$
      minDelayMs:
        type: number
        minimum: 0
      maxDelayMs:
        type: number
        minimum: 0
      minDurationMs:
        type: number
        minimum: 0
      maxDurationMs:
        type: number
        minimum: 0
      type:
        type: string
        enum:
          - event-card
      markerSlot:
        $ref: '#/definitions/BasicSlotConfig'
      cardSlots:
        type: array
        items:
          $ref: '#/definitions/CardSlotConfig'
      cards:
        type: array
        items:
          $ref: '#/definitions/CardConfig'
    required:
      - id
      - minDelayMs
      - maxDelayMs
      - minDurationMs
      - maxDurationMs
      - type
      - markerSlot
      - cardSlots
      - cards
    additionalProperties: false
  SlotGroup:
    anyOf:
      - $ref: '#/definitions/BasicSlotGroupConfig'
      - $ref: '#/definitions/ActionCardSlotGroupConfig'
      - $ref: '#/definitions/EventCardSlotGroupConfig'
  TriggerConditionConfig:
    type: object
    properties:
      condition:
        type: string
      url:
        type: string
        pattern: _x[+-]?[0-9]+_y[+-]?[0-9]+\.[a-zA-Z0-9]+$
    required:
      - condition
      - url
    additionalProperties: false
  TriggerConfig:
    type: object
    properties:
      id:
        type: string
      events:
        type: array
        items:
          $ref: '#/definitions/TriggerConditionConfig'
    required:
      - id
      - events
    additionalProperties: false
